-- +goose Up
CREATE TABLE `users` (
  `uid` INT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `name` VARCHAR(50) COLLATE utf8mb4_bin NOT NULL COMMENT 'ユーザー名',
  `age` INT NOT NULL COMMENT '年齢',
  `gendar` INT NOT NULL COMMENT '性別 0:男 1:女',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(`uid`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = 'ユーザー';

-- +goose Down
DROP TABLE IF EXISTS `users`;